export const Currencies = [
  { name: "AFN - Afghan Afghani", value: "afn" },
  { name: "ALL - Albanian Lek", value: "all" },
  { name: "DZD - Algerian Dinar", value: "dzd" },
  { name: "USD - United States Dollar", value: "usd" },
  { name: "EUR - Euro", value: "eur" },
  { name: "AOA - Angolan Kwanza", value: "aoa" },
  { name: "XCD - East Caribbean Dollar", value: "xcd" },
  { name: "ARS - Argentine Peso", value: "ars" },
  { name: "AMD - Armenian Dram", value: "amd" },
  { name: "AWG - Aruban Florin", value: "awg" },
  { name: "AUD - Australian Dollar", value: "aud" },
  { name: "AZN - Azerbaijani Manat", value: "azn" },
  { name: "BSD - Bahamian Dollar", value: "bsd" },
  { name: "BHD - Bahraini Dinar", value: "bhd" },
  { name: "BDT - Bangladeshi Taka", value: "bdt" },
  { name: "BBD - Barbadian Dollar", value: "bbd" },
  { name: "BYN - Belarusian Ruble", value: "byn" },
  { name: "BZD - Belize Dollar", value: "bzd" },
  { name: "XOF - CFA Franc BCEAO", value: "xof" },
  { name: "BMD - Bermudian Dollar", value: "bmd" },
  { name: "BTN - Bhutanese Ngultrum", value: "btn" },
  { name: "BOB - Bolivian Boliviano", value: "bob" },
  { name: "BOV - Bolivian Mvdol", value: "bov" },
  { name: "BAM - Bosnia and Herzegovina Convertible Mark", value: "bam" },
  { name: "BWP - Botswana Pula", value: "bwp" },
  { name: "BRL - Brazilian Real", value: "brl" },
  { name: "BND - Brunei Dollar", value: "bnd" },
  { name: "BGN - Bulgarian Lev", value: "bgn" },
  { name: "BIF - Burundian Franc", value: "bif" },
  { name: "KHR - Cambodian Riel", value: "khr" },
  { name: "CAD - Canadian Dollar", value: "cad" },
  { name: "CVE - Cape Verdean Escudo", value: "cve" },
  { name: "KYD - Cayman Islands Dollar", value: "kyd" },
  { name: "XAF - Central African CFA Franc", value: "xaf" },
  { name: "CLP - Chilean Peso", value: "clp" },
  { name: "CNY - Chinese Yuan", value: "cny" },
  { name: "COP - Colombian Peso", value: "cop" },
  { name: "KMF - Comorian Franc", value: "kmf" },
  { name: "CDF - Congolese Franc", value: "cdf" },
  { name: "CRC - Costa Rican Colón", value: "crc" },
  { name: "HRK - Croatian Kuna", value: "hrk" },
  { name: "CUP - Cuban Peso", value: "cup" },
  { name: "CZK - Czech Koruna", value: "czk" },
  { name: "DKK - Danish Krone", value: "dkk" },
  { name: "DJF - Djiboutian Franc", value: "djf" },
  { name: "DOP - Dominican Peso", value: "dop" },
  { name: "EGP - Egyptian Pound", value: "egp" },
  { name: "ERN - Eritrean Nakfa", value: "ern" },
  { name: "SZL - Eswatini Lilangeni", value: "szl" },
  { name: "ETB - Ethiopian Birr", value: "etb" },
  { name: "FJD - Fijian Dollar", value: "fjd" },
  { name: "GMD - Gambian Dalasi", value: "gmd" },
  { name: "GEL - Georgian Lari", value: "gel" },
  { name: "GHS - Ghanaian Cedi", value: "ghs" },
  { name: "GIP - Gibraltar Pound", value: "gip" },
  { name: "GTQ - Guatemalan Quetzal", value: "gtq" },
  { name: "GNF - Guinean Franc", value: "gnf" },
  { name: "GYD - Guyanese Dollar", value: "gyd" },
  { name: "HTG - Haitian Gourde", value: "htg" },
  { name: "HNL - Honduran Lempira", value: "hnl" },
  { name: "HKD - Hong Kong Dollar", value: "hkd" },
  { name: "HUF - Hungarian Forint", value: "huf" },
  { name: "ISK - Icelandic Króna", value: "isk" },
  { name: "INR - Indian Rupee", value: "inr" },
  { name: "IDR - Indonesian Rupiah", value: "idr" },
  { name: "IRR - Iranian Rial", value: "irr" },
  { name: "IQD - Iraqi Dinar", value: "iqd" },
  { name: "ILS - Israeli New Shekel", value: "ils" },
  { name: "JMD - Jamaican Dollar", value: "jmd" },
  { name: "JPY - Japanese Yen", value: "jpy" },
  { name: "JOD - Jordanian Dinar", value: "jod" },
];

export const videoOptions = [
  { key: "embed", value: "Embed" },
  { key: "directVideo", value: "Direct Video (.mp4, .webm, .avi, .mov etc.)" },
  { key: "adaptive", value: "Adaptive Stream (hls, dash)" },
  { key: "basicUrl", value: "Basic Url" },
];

export const QualityOptions = [
  { key: "regular", value: "Regular" },
  { key: "sd", value: "SD" },
  { key: "hd", value: "HD" },
  { key: "720", value: "720p" },
  { key: "1080", value: "1080p" },
  { key: "4k", value: "4K" },
];

export const languageOptions = [
  { key: "english", value: "English" },
  { key: "french", value: "French" },
  { key: "spanish", value: "Spanish" },
  { key: "german", value: "German" },
  { key: "chinese", value: "Chinese" },
];

export const videoCategory = [
  { key: "movie", value: "Movie" },
  { key: "tvShow", value: "TV Show" },
  { key: "documentary", value: "Documentary" },
  { key: "musicVideo", value: "Music Video" },
  { key: "sports", value: "Sports" },
  { key: "news", value: "News" },
  { key: "education", value: "Education" },
  { key: "entertainment", value: "Entertainment" },
  { key: "gaming", value: "Gaming" },
  { key: "lifestyle", value: "Lifestyle" },
];

export const categoryOptions = [
  { label: "Trailer", value: "trailer" },
  { label: "Clip", value: "clip" },
  { label: "Featurette", value: "featurette" },
  { label: "Teaser", value: "teaser" },
  { label: "Full Movie or Episode", value: "full" },
];

export const countryOptions = [
  { name: "United States", value: "United-States" },
  { name: "Canada", value: "Canada" },
  { name: "United Kingdom", value: "United-Kingdom" },
  { name: "Australia", value: "Australia" },
  { name: "Germany", value: "Germany" },
  { name: "France", value: "France" },
  { name: "Japan", value: "Japan" },
  { name: "India", value: "India" },
  { name: "Brazil", value: "Brazil" },
  { name: "South Africa", value: "South-Africa" },
];

export const genderOption =  [
  { label: "male", value: "Male" },
  { label: "female", value: "Female" },
  { label: "other", value: "Other" },
];