export { default as SideBar } from "./SideBar";
export { default as TopHeader } from "./TopHeader"; 
export { default as SettingSideBar } from "./SettingSideBar";
export { default as Error } from "./Error";
export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Slider } from "./Slider";
export { default as SliderNumber } from "./SliderNumber";
export { default as TopicSlider } from "./TopicSlider";